# Generated by Django 5.0.6 on 2024-12-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0015_bb_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bb_method',
        ),
    ]
