# Generated by Django 5.0.6 on 2024-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_delete_bb_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
