# Generated by Django 5.0.6 on 2024-12-10 15:01

import django.core.validators
import django.db.models.deletion
import precise_bbcode.fields
import testapp.bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название')),
                ('order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[(None, 'Выберите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю')], default='s', max_length=1)),
                ('title', models.CharField(error_messages={'invalid': 'Неправильное название товара!'}, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', message='Слишком мало букавак!', regex='^.{4,}$')], verbose_name='Товар')),
                ('_content_rendered', models.TextField(blank=True, editable=False, null=True)),
                ('content', precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[testapp.bboard.models.validate_even], verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('img', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='testapp.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published', 'title'],
                'get_latest_by': 'published',
            },
        ),
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-order', '-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.rubric',),
        ),
    ]
