# Generated by Django 5.1.4 on 2024-12-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dark', 'Черный юмор'), ('jokes300', 'Шутки за 300'), ('knockknock', 'Тук-тук шутки'), ('army', 'Армейские анекдоты')], max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
