# Generated by Django 5.1.4 on 2024-12-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(choices=[('dark', 'Черный юмор'), ('jokes300', 'Шутки за 300'), ('knockknock', 'Тук-тук шутки'), ('army', 'Армейские анекдоты')], max_length=20),
        ),
    ]
